version: "3.3"

services:
  tuleap:
    image: enalean/tuleap-aio
    container_name: tuleap
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - tuleap-data:/data
      - tuleap-conf:/etc/tuleap
      - tuleap-log:/var/log/tuleap

volumes:
  tuleap-data:
  tuleap-conf:
  tuleap-log:
