version: "3.3"

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:6875
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=secretpassword
      - DB_DATABASE=bookstackapp
      - APP_KEY=base64:rQPfr2DyP5c+svc53NHy9RMdE67+RL3DJ37QAXE/rLQ=
    volumes:
      - bookstack_data:/config
    ports:
      - "6875:80"
    depends_on:
      - bookstack_db
    restart: unless-stopped

  bookstack_db:
    image: mariadb:10.5
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=secretpassword
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=secretpassword
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  bookstack_data:
  db_data:
